package ui;

import collections.LinkedList;

/**
 *
 * @author Rickolas-PC
 */
public class SetupUI extends javax.swing.JFrame {
    
    final private String wholeNote = "Whole Note";
    final private String halfNote = "Half Note";
    final private String quarterNote = "Quarter Note";
    final private String eighthNote = "Eighth Note";
    final private String sixteenthNote = "Sixteenth Note";
    final private String thirtysecondNote = "Thirty-Second Note";
    final private double wholeNoteNum = 4;
    final private double halfNoteNum = 2;
    final private double quarterNoteNum = 1;
    final private double eighthNoteNum = 0.5;
    final private double sixteenthNoteNum = 0.25;
    final private double thirtysecondNoteNum = 0.125;
    
    final private String wholeRest = "Whole Rest";
    final private String halfRest = "Half Rest";
    final private String quarterRest = "Quarter Rest";
    final private String eighthRest = "Eighth Rest";
    final private String sixteenthRest = "Sixteenth Rest";
    final private String thirtysecondRest = "Thirty-Second Rest";
    final private double wholeRestNum = 4;
    final private double halfRestNum = 2;
    final private double quarterRestNum = 1;
    final private double eighthRestNum = 0.5;
    final private double sixteenthRestNum = 0.25;
    final private double thirtysecondRestNum = 0.125;
    
    private SetupUIController controller;
    
    /**
     * Creates new form SetupUI
     */
    public SetupUI() {
        initComponents();
    }
    
    public SetupUI(LinkedList displaySheets) {
        initComponents();
        controller = new SetupUIController(displaySheets, tbdSetup, pnlSetup, 
                pnlTreble, pnlBass, lblSetupSheet, txtMessureNum, 
                txtMessureBeats, txtTempo, btnSSNext, btnTrebleIntCon, 
                btnTrebleWholeNote, btnTrebleHalfNote, btnTrebleQuarterNote, 
                btnTrebleEighthNote, btnTrebleSixteenthNote, 
                btnTrebleThirtysecondNote, btnTrebleWholeRest, 
                btnTrebleHalfRest, btnTrebleQuarterRest, 
                btnTrebleEighthRest, btnTrebleSixteenthRest, 
                btnTrebleThirtysecondRest, cmbTrebleNote, cmbTrebleOctave, 
                chkTrebleTriplet, chkTrebleInterval, btnTrebleNext, 
                btnBassIntCon, btnBassWholeNote, btnBassHalfNote, 
                btnBassQuarterNote, btnBassEighthNote, btnBassSixteenthNote,
                btnBassThirtysecondNote, btnBassWholeRest, btnBassHalfRest, 
                btnBassQuarterRest, btnBassEighthRest, btnBassSixteenthRest, 
                btnBassThirtysecondRest, cmbBassNote, cmbBassOctave, 
                chkBassTriplet, chkBassInterval, btnBassNext, lstSoundInfo,
                lstTrebleSoundInfo, lstBassSoundInfo, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSetupSheet = new javax.swing.JLabel();
        tbdSetup = new javax.swing.JTabbedPane();
        pnlSetup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSSNext = new javax.swing.JButton();
        txtMessureBeats = new javax.swing.JTextField();
        txtMessureNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();
        pnlTreble = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnTrebleWholeNote = new javax.swing.JButton();
        btnTrebleHalfNote = new javax.swing.JButton();
        btnTrebleQuarterNote = new javax.swing.JButton();
        btnTrebleEighthNote = new javax.swing.JButton();
        btnTrebleSixteenthNote = new javax.swing.JButton();
        btnTrebleThirtysecondNote = new javax.swing.JButton();
        chkTrebleTriplet = new javax.swing.JCheckBox();
        cmbTrebleNote = new javax.swing.JComboBox<>();
        chkTrebleInterval = new javax.swing.JCheckBox();
        btnTrebleIntCon = new javax.swing.JButton();
        cmbTrebleOctave = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        btnTrebleWholeRest = new javax.swing.JButton();
        btnTrebleHalfRest = new javax.swing.JButton();
        btnTrebleQuarterRest = new javax.swing.JButton();
        btnTrebleEighthRest = new javax.swing.JButton();
        btnTrebleSixteenthRest = new javax.swing.JButton();
        btnTrebleThirtysecondRest = new javax.swing.JButton();
        btnTrebleNext = new javax.swing.JButton();
        pnlBass = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnBassWholeNote = new javax.swing.JButton();
        btnBassHalfNote = new javax.swing.JButton();
        btnBassQuarterNote = new javax.swing.JButton();
        btnBassEighthNote = new javax.swing.JButton();
        btnBassSixteenthNote = new javax.swing.JButton();
        btnBassThirtysecondNote = new javax.swing.JButton();
        chkBassTriplet = new javax.swing.JCheckBox();
        cmbBassNote = new javax.swing.JComboBox<>();
        chkBassInterval = new javax.swing.JCheckBox();
        btnBassIntCon = new javax.swing.JButton();
        cmbBassOctave = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        btnBassWholeRest = new javax.swing.JButton();
        btnBassHalfRest = new javax.swing.JButton();
        btnBassQuarterRest = new javax.swing.JButton();
        btnBassEighthRest = new javax.swing.JButton();
        btnBassSixteenthRest = new javax.swing.JButton();
        btnBassThirtysecondRest = new javax.swing.JButton();
        btnBassNext = new javax.swing.JButton();
        lstBassSoundInfo = new java.awt.List();
        lstSoundInfo = new java.awt.List();
        lstTrebleSoundInfo = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lblSetupSheet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetupSheet.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbdSetup.setEnabled(false);
        tbdSetup.setName(""); // NOI18N

        pnlSetup.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Page 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        jLabel1.setText("Number of Messures:");

        jLabel2.setText("Beats Per Messure:");

        btnSSNext.setText("Next");
        btnSSNext.setEnabled(false);
        btnSSNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSSNextActionPerformed(evt);
            }
        });

        txtMessureBeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMessureBeatsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMessureBeatsKeyTyped(evt);
            }
        });

        txtMessureNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMessureNumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMessureNumKeyTyped(evt);
            }
        });

        jLabel3.setText("Tempo:");

        txtTempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTempoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTempoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlSetupLayout = new javax.swing.GroupLayout(pnlSetup);
        pnlSetup.setLayout(pnlSetupLayout);
        pnlSetupLayout.setHorizontalGroup(
            pnlSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSetupLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSSNext))
                    .addGroup(pnlSetupLayout.createSequentialGroup()
                        .addGroup(pnlSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlSetupLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMessureBeats, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlSetupLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMessureNum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlSetupLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(75, 75, 75)
                                .addComponent(txtTempo)))
                        .addGap(0, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSetupLayout.setVerticalGroup(
            pnlSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMessureNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMessureBeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnSSNext)
                .addContainerGap())
        );

        tbdSetup.addTab("Score Setup", pnlSetup);

        pnlTreble.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Page 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        btnTrebleWholeNote.setText("Whole Note");
        btnTrebleWholeNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleWholeNoteActionPerformed(evt);
            }
        });

        btnTrebleHalfNote.setText("Half Note");
        btnTrebleHalfNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleHalfNoteActionPerformed(evt);
            }
        });

        btnTrebleQuarterNote.setText("Quarter Note");
        btnTrebleQuarterNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleQuarterNoteActionPerformed(evt);
            }
        });

        btnTrebleEighthNote.setText("Eighth Note");
        btnTrebleEighthNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleEighthNoteActionPerformed(evt);
            }
        });

        btnTrebleSixteenthNote.setText("Sixteenth Note");
        btnTrebleSixteenthNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleSixteenthNoteActionPerformed(evt);
            }
        });

        btnTrebleThirtysecondNote.setText("Thirty-Second Note");
        btnTrebleThirtysecondNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleThirtysecondNoteActionPerformed(evt);
            }
        });

        chkTrebleTriplet.setText("Triplet");
        chkTrebleTriplet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkTrebleTripletStateChanged(evt);
            }
        });

        cmbTrebleNote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A#", "B", "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#" }));
        cmbTrebleNote.setBorder(javax.swing.BorderFactory.createTitledBorder("Note"));

        chkTrebleInterval.setText("Interval");
        chkTrebleInterval.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkTrebleIntervalStateChanged(evt);
            }
        });

        btnTrebleIntCon.setText("Confirm");
        btnTrebleIntCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleIntConActionPerformed(evt);
            }
        });

        cmbTrebleOctave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbTrebleOctave.setBorder(javax.swing.BorderFactory.createTitledBorder("Octave"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTrebleWholeNote, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(btnTrebleEighthNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTrebleHalfNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrebleSixteenthNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTrebleThirtysecondNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrebleQuarterNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbTrebleNote, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTrebleOctave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkTrebleTriplet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkTrebleInterval)
                        .addGap(18, 18, 18)
                        .addComponent(btnTrebleIntCon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrebleQuarterNote)
                    .addComponent(btnTrebleHalfNote)
                    .addComponent(btnTrebleWholeNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrebleSixteenthNote)
                    .addComponent(btnTrebleThirtysecondNote)
                    .addComponent(btnTrebleEighthNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTrebleOctave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkTrebleTriplet)
                            .addComponent(chkTrebleInterval)
                            .addComponent(btnTrebleIntCon)))
                    .addComponent(cmbTrebleNote, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        btnTrebleWholeRest.setText("Whole Rest");
        btnTrebleWholeRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleWholeRestActionPerformed(evt);
            }
        });

        btnTrebleHalfRest.setText("Half Rest");
        btnTrebleHalfRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleHalfRestActionPerformed(evt);
            }
        });

        btnTrebleQuarterRest.setText("Quarter Rest");
        btnTrebleQuarterRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleQuarterRestActionPerformed(evt);
            }
        });

        btnTrebleEighthRest.setText("Eighth Rest");
        btnTrebleEighthRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleEighthRestActionPerformed(evt);
            }
        });

        btnTrebleSixteenthRest.setText("Sixteenth Rest");
        btnTrebleSixteenthRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleSixteenthRestActionPerformed(evt);
            }
        });

        btnTrebleThirtysecondRest.setText("Thirty-Second Rest");
        btnTrebleThirtysecondRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleThirtysecondRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTrebleWholeRest, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnTrebleEighthRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTrebleHalfRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrebleSixteenthRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTrebleThirtysecondRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrebleQuarterRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrebleQuarterRest)
                    .addComponent(btnTrebleHalfRest)
                    .addComponent(btnTrebleWholeRest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrebleSixteenthRest)
                    .addComponent(btnTrebleThirtysecondRest)
                    .addComponent(btnTrebleEighthRest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTrebleNext.setText("Next");
        btnTrebleNext.setEnabled(false);
        btnTrebleNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTrebleLayout = new javax.swing.GroupLayout(pnlTreble);
        pnlTreble.setLayout(pnlTrebleLayout);
        pnlTrebleLayout.setHorizontalGroup(
            pnlTrebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrebleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTrebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrebleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTrebleNext)
                .addContainerGap())
        );
        pnlTrebleLayout.setVerticalGroup(
            pnlTrebleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrebleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrebleNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdSetup.addTab("Treble Clef", pnlTreble);

        pnlBass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Page 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        btnBassWholeNote.setText("Whole Note");
        btnBassWholeNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassWholeNoteActionPerformed(evt);
            }
        });

        btnBassHalfNote.setText("Half Note");
        btnBassHalfNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassHalfNoteActionPerformed(evt);
            }
        });

        btnBassQuarterNote.setText("Quarter Note");
        btnBassQuarterNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassQuarterNoteActionPerformed(evt);
            }
        });

        btnBassEighthNote.setText("Eighth Note");
        btnBassEighthNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassEighthNoteActionPerformed(evt);
            }
        });

        btnBassSixteenthNote.setText("Sixteenth Note");
        btnBassSixteenthNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassSixteenthNoteActionPerformed(evt);
            }
        });

        btnBassThirtysecondNote.setText("Thirty-Second Note");
        btnBassThirtysecondNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassThirtysecondNoteActionPerformed(evt);
            }
        });

        chkBassTriplet.setText("Triplet");
        chkBassTriplet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBassTripletStateChanged(evt);
            }
        });

        cmbBassNote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A#", "B", "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#" }));
        cmbBassNote.setBorder(javax.swing.BorderFactory.createTitledBorder("Note"));

        chkBassInterval.setText("Interval");
        chkBassInterval.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBassIntervalStateChanged(evt);
            }
        });

        btnBassIntCon.setText("Confirm");
        btnBassIntCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassIntConActionPerformed(evt);
            }
        });

        cmbBassOctave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbBassOctave.setBorder(javax.swing.BorderFactory.createTitledBorder("Octave"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBassWholeNote, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(btnBassEighthNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBassHalfNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBassSixteenthNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBassThirtysecondNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBassQuarterNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(cmbBassNote, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBassOctave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkBassTriplet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkBassInterval)
                        .addGap(18, 18, 18)
                        .addComponent(btnBassIntCon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBassQuarterNote)
                    .addComponent(btnBassHalfNote)
                    .addComponent(btnBassWholeNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBassSixteenthNote)
                    .addComponent(btnBassThirtysecondNote)
                    .addComponent(btnBassEighthNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBassOctave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBassTriplet)
                            .addComponent(chkBassInterval)
                            .addComponent(btnBassIntCon)))
                    .addComponent(cmbBassNote, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        btnBassWholeRest.setText("Whole Rest");
        btnBassWholeRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassWholeRestActionPerformed(evt);
            }
        });

        btnBassHalfRest.setText("Half Rest");
        btnBassHalfRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassHalfRestActionPerformed(evt);
            }
        });

        btnBassQuarterRest.setText("Quarter Rest");
        btnBassQuarterRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassQuarterRestActionPerformed(evt);
            }
        });

        btnBassEighthRest.setText("Eighth Rest");
        btnBassEighthRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassEighthRestActionPerformed(evt);
            }
        });

        btnBassSixteenthRest.setText("Sixteenth Rest");
        btnBassSixteenthRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassSixteenthRestActionPerformed(evt);
            }
        });

        btnBassThirtysecondRest.setText("Thirty-Second Rest");
        btnBassThirtysecondRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassThirtysecondRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBassWholeRest, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnBassEighthRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBassHalfRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBassSixteenthRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBassThirtysecondRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBassQuarterRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBassQuarterRest)
                    .addComponent(btnBassHalfRest)
                    .addComponent(btnBassWholeRest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBassSixteenthRest)
                    .addComponent(btnBassThirtysecondRest)
                    .addComponent(btnBassEighthRest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBassNext.setText("Next");
        btnBassNext.setEnabled(false);
        btnBassNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBassNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBassLayout = new javax.swing.GroupLayout(pnlBass);
        pnlBass.setLayout(pnlBassLayout);
        pnlBassLayout.setHorizontalGroup(
            pnlBassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBassNext)
                .addContainerGap())
        );
        pnlBassLayout.setVerticalGroup(
            pnlBassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBassNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdSetup.addTab("Base Clef", pnlBass);

        lstBassSoundInfo.setName(""); // NOI18N

        lstSoundInfo.setName(""); // NOI18N

        lstTrebleSoundInfo.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbdSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lstBassSoundInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(lstTrebleSoundInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lstSoundInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblSetupSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSetupSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbdSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lstSoundInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lstTrebleSoundInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lstBassSoundInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        tbdSetup.getAccessibleContext().setAccessibleName("tab 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessureNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessureNumKeyTyped
        controller.integerTest(evt);
    }//GEN-LAST:event_txtMessureNumKeyTyped

    private void txtMessureBeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessureBeatsKeyTyped
        controller.integerTest(evt);
    }//GEN-LAST:event_txtMessureBeatsKeyTyped

    private void txtMessureNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessureNumKeyReleased
        controller.fieldCheck();
    }//GEN-LAST:event_txtMessureNumKeyReleased

    private void txtMessureBeatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessureBeatsKeyReleased
        controller.fieldCheck();
    }//GEN-LAST:event_txtMessureBeatsKeyReleased

    private void btnSSNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSSNextActionPerformed
        boolean pageFinish = false;
        controller.nextTab(pageFinish);
    }//GEN-LAST:event_btnSSNextActionPerformed

    private void txtTempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempoKeyTyped
        controller.integerTest(evt);
    }//GEN-LAST:event_txtTempoKeyTyped

    private void txtTempoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempoKeyReleased
        controller.fieldCheck();
    }//GEN-LAST:event_txtTempoKeyReleased

    private void btnTrebleNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleNextActionPerformed
        boolean pageFinish = false;
        controller.nextTab(pageFinish);
    }//GEN-LAST:event_btnTrebleNextActionPerformed

    private void btnTrebleWholeNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleWholeNoteActionPerformed
        controller.addTrebleNote(wholeNote, wholeNoteNum);
    }//GEN-LAST:event_btnTrebleWholeNoteActionPerformed

    private void btnTrebleHalfNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleHalfNoteActionPerformed
        controller.addTrebleNote(halfNote, halfNoteNum);
    }//GEN-LAST:event_btnTrebleHalfNoteActionPerformed

    private void btnTrebleQuarterNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleQuarterNoteActionPerformed
        controller.addTrebleNote(quarterNote, quarterNoteNum);
    }//GEN-LAST:event_btnTrebleQuarterNoteActionPerformed

    private void btnTrebleEighthNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleEighthNoteActionPerformed
        controller.addTrebleNote(eighthNote, eighthNoteNum);
    }//GEN-LAST:event_btnTrebleEighthNoteActionPerformed

    private void btnTrebleSixteenthNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleSixteenthNoteActionPerformed
        controller.addTrebleNote(sixteenthNote, sixteenthNoteNum);
    }//GEN-LAST:event_btnTrebleSixteenthNoteActionPerformed

    private void btnTrebleThirtysecondNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleThirtysecondNoteActionPerformed
        controller.addTrebleNote(thirtysecondNote, thirtysecondNoteNum);
    }//GEN-LAST:event_btnTrebleThirtysecondNoteActionPerformed

    private void btnTrebleIntConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleIntConActionPerformed
        controller.trebleMerge();
    }//GEN-LAST:event_btnTrebleIntConActionPerformed

    private void chkTrebleIntervalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkTrebleIntervalStateChanged
        controller.trebleButtonUpdate();
    }//GEN-LAST:event_chkTrebleIntervalStateChanged

    private void btnTrebleWholeRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleWholeRestActionPerformed
        controller.addTrebleRest(wholeRest, wholeRestNum);
    }//GEN-LAST:event_btnTrebleWholeRestActionPerformed

    private void btnTrebleHalfRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleHalfRestActionPerformed
        controller.addTrebleRest(halfRest, halfRestNum);
    }//GEN-LAST:event_btnTrebleHalfRestActionPerformed

    private void btnTrebleQuarterRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleQuarterRestActionPerformed
        controller.addTrebleRest(quarterRest, quarterRestNum);
    }//GEN-LAST:event_btnTrebleQuarterRestActionPerformed

    private void btnTrebleEighthRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleEighthRestActionPerformed
        controller.addTrebleRest(eighthRest, eighthRestNum);
    }//GEN-LAST:event_btnTrebleEighthRestActionPerformed

    private void btnTrebleSixteenthRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleSixteenthRestActionPerformed
        controller.addTrebleRest(sixteenthRest, sixteenthRestNum);
    }//GEN-LAST:event_btnTrebleSixteenthRestActionPerformed

    private void btnTrebleThirtysecondRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleThirtysecondRestActionPerformed
        controller.addTrebleRest(thirtysecondRest,thirtysecondRestNum);
    }//GEN-LAST:event_btnTrebleThirtysecondRestActionPerformed

    private void btnBassWholeNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassWholeNoteActionPerformed
        controller.addBassNote(wholeNote, wholeNoteNum);
    }//GEN-LAST:event_btnBassWholeNoteActionPerformed

    private void btnBassHalfNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassHalfNoteActionPerformed
        controller.addBassNote(halfNote, halfNoteNum);
    }//GEN-LAST:event_btnBassHalfNoteActionPerformed

    private void btnBassQuarterNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassQuarterNoteActionPerformed
        controller.addBassNote(quarterNote, quarterNoteNum);
    }//GEN-LAST:event_btnBassQuarterNoteActionPerformed

    private void btnBassEighthNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassEighthNoteActionPerformed
        controller.addBassNote(eighthNote, eighthNoteNum);
    }//GEN-LAST:event_btnBassEighthNoteActionPerformed

    private void btnBassSixteenthNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassSixteenthNoteActionPerformed
        controller.addBassNote(sixteenthNote, sixteenthNoteNum);
    }//GEN-LAST:event_btnBassSixteenthNoteActionPerformed

    private void btnBassThirtysecondNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassThirtysecondNoteActionPerformed
        controller.addBassNote(thirtysecondNote, thirtysecondNoteNum);
    }//GEN-LAST:event_btnBassThirtysecondNoteActionPerformed

    private void chkBassIntervalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBassIntervalStateChanged
        controller.bassButtonUpdate();
    }//GEN-LAST:event_chkBassIntervalStateChanged

    private void btnBassIntConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassIntConActionPerformed
        controller.bassMerge();
    }//GEN-LAST:event_btnBassIntConActionPerformed

    private void btnBassWholeRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassWholeRestActionPerformed
        controller.addBassRest(wholeRest, wholeRestNum);
    }//GEN-LAST:event_btnBassWholeRestActionPerformed

    private void btnBassHalfRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassHalfRestActionPerformed
        controller.addBassRest(halfRest, halfRestNum);
    }//GEN-LAST:event_btnBassHalfRestActionPerformed

    private void btnBassQuarterRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassQuarterRestActionPerformed
        controller.addBassRest(quarterRest, quarterRestNum);
    }//GEN-LAST:event_btnBassQuarterRestActionPerformed

    private void btnBassEighthRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassEighthRestActionPerformed
        controller.addBassRest(eighthRest, eighthRestNum);
    }//GEN-LAST:event_btnBassEighthRestActionPerformed

    private void btnBassSixteenthRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassSixteenthRestActionPerformed
        controller.addBassRest(sixteenthRest, sixteenthRestNum);
    }//GEN-LAST:event_btnBassSixteenthRestActionPerformed

    private void btnBassThirtysecondRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassThirtysecondRestActionPerformed
        controller.addBassRest(thirtysecondRest, thirtysecondRestNum);
    }//GEN-LAST:event_btnBassThirtysecondRestActionPerformed

    private void btnBassNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBassNextActionPerformed
        boolean pageFinish = true;
        controller.nextTab(pageFinish);
    }//GEN-LAST:event_btnBassNextActionPerformed

    private void chkTrebleTripletStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkTrebleTripletStateChanged
        controller.trebleButtonUpdate();
    }//GEN-LAST:event_chkTrebleTripletStateChanged

    private void chkBassTripletStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBassTripletStateChanged
        controller.bassButtonUpdate();
    }//GEN-LAST:event_chkBassTripletStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBassEighthNote;
    private javax.swing.JButton btnBassEighthRest;
    private javax.swing.JButton btnBassHalfNote;
    private javax.swing.JButton btnBassHalfRest;
    private javax.swing.JButton btnBassIntCon;
    private javax.swing.JButton btnBassNext;
    private javax.swing.JButton btnBassQuarterNote;
    private javax.swing.JButton btnBassQuarterRest;
    private javax.swing.JButton btnBassSixteenthNote;
    private javax.swing.JButton btnBassSixteenthRest;
    private javax.swing.JButton btnBassThirtysecondNote;
    private javax.swing.JButton btnBassThirtysecondRest;
    private javax.swing.JButton btnBassWholeNote;
    private javax.swing.JButton btnBassWholeRest;
    private javax.swing.JButton btnSSNext;
    private javax.swing.JButton btnTrebleEighthNote;
    private javax.swing.JButton btnTrebleEighthRest;
    private javax.swing.JButton btnTrebleHalfNote;
    private javax.swing.JButton btnTrebleHalfRest;
    private javax.swing.JButton btnTrebleIntCon;
    private javax.swing.JButton btnTrebleNext;
    private javax.swing.JButton btnTrebleQuarterNote;
    private javax.swing.JButton btnTrebleQuarterRest;
    private javax.swing.JButton btnTrebleSixteenthNote;
    private javax.swing.JButton btnTrebleSixteenthRest;
    private javax.swing.JButton btnTrebleThirtysecondNote;
    private javax.swing.JButton btnTrebleThirtysecondRest;
    private javax.swing.JButton btnTrebleWholeNote;
    private javax.swing.JButton btnTrebleWholeRest;
    private javax.swing.JCheckBox chkBassInterval;
    private javax.swing.JCheckBox chkBassTriplet;
    private javax.swing.JCheckBox chkTrebleInterval;
    private javax.swing.JCheckBox chkTrebleTriplet;
    private javax.swing.JComboBox<String> cmbBassNote;
    private javax.swing.JComboBox<String> cmbBassOctave;
    private javax.swing.JComboBox<String> cmbTrebleNote;
    private javax.swing.JComboBox<String> cmbTrebleOctave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblSetupSheet;
    private java.awt.List lstBassSoundInfo;
    private java.awt.List lstSoundInfo;
    private java.awt.List lstTrebleSoundInfo;
    private javax.swing.JPanel pnlBass;
    private javax.swing.JPanel pnlSetup;
    private javax.swing.JPanel pnlTreble;
    private javax.swing.JTabbedPane tbdSetup;
    private javax.swing.JTextField txtMessureBeats;
    private javax.swing.JTextField txtMessureNum;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
