package ui;

import collections.LinkedList;

/**
 *
 * @author Rickolas-PC
 */
public class SetupUI extends javax.swing.JFrame {
    
    final private String wholeNote = "Whole Note";
    final private String halfNote = "Half Note";
    final private String quarterNote = "Quarter Note";
    final private String eighthNote = "Eighth Note";
    final private String sixteenthNote = "Sixteenth Note";
    final private String thirtysecondNote = "Thirty-Second Note";
    final private double wholeNoteNum = 4;
    final private double halfNoteNum = 2;
    final private double quarterNoteNum = 1;
    final private double eighthNoteNum = 0.5;
    final private double sixteenthNoteNum = 0.25;
    final private double thirtysecondNoteNum = 0.125;
    
    final private String wholeRest = "Whole Rest";
    final private String halfRest = "Half Rest";
    final private String quarterRest = "Quarter Rest";
    final private String eighthRest = "Eighth Rest";
    final private String sixteenthRest = "Sixteenth Rest";
    final private String thirtysecondRest = "Thirty-Second Rest";
    final private double wholeRestNum = 4;
    final private double halfRestNum = 2;
    final private double quarterRestNum = 1;
    final private double eighthRestNum = 0.5;
    final private double sixteenthRestNum = 0.25;
    final private double thirtysecondRestNum = 0.125;
    
    private SetupUIController controller;
    
    /**
     * Creates new form SetupUI
     */
    public SetupUI() {
        initComponents();
    }
    
    public SetupUI(LinkedList displaySheets) {
        initComponents();
        controller = new SetupUIController(displaySheets, tabSetup, 
                lblSetupSheet, txtMessureNum, txtMessureBeats, txtTempo, 
                btnSSNext, btnTrebleIntCon, btnTrebleWholeNote, btnTrebleHalfNote, 
                btnTrebleQuarterNote, btnTrebleEighthNote, btnTrebleSixteenthNote, 
                btnTrebleThirtysecondNote, btnTrebleWholeRest, btnTrebleHalfRest, btnTrebleQuarterRest, 
                btnTrebleEighthRest, btnTrebleSixteenthRest, btnTrebleThirtysecondRest, 
                cmbTrebleNote, cmbTrebleOctave, chkTrebleTriplet, chkTrebleInterval, 
                btnTrebleNext, lstSoundInfo, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSetupSheet = new javax.swing.JLabel();
        tabSetup = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSSNext = new javax.swing.JButton();
        txtMessureBeats = new javax.swing.JTextField();
        txtMessureNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnTrebleWholeNote = new javax.swing.JButton();
        btnTrebleHalfNote = new javax.swing.JButton();
        btnTrebleQuarterNote = new javax.swing.JButton();
        btnTrebleEighthNote = new javax.swing.JButton();
        btnTrebleSixteenthNote = new javax.swing.JButton();
        btnTrebleThirtysecondNote = new javax.swing.JButton();
        chkTrebleTriplet = new javax.swing.JCheckBox();
        cmbTrebleNote = new javax.swing.JComboBox<>();
        chkTrebleInterval = new javax.swing.JCheckBox();
        btnTrebleIntCon = new javax.swing.JButton();
        cmbTrebleOctave = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        btnTrebleWholeRest = new javax.swing.JButton();
        btnTrebleHalfRest = new javax.swing.JButton();
        btnTrebleQuarterRest = new javax.swing.JButton();
        btnTrebleEighthRest = new javax.swing.JButton();
        btnTrebleSixteenthRest = new javax.swing.JButton();
        btnTrebleThirtysecondRest = new javax.swing.JButton();
        btnTrebleNext = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnBaseWholeNote = new javax.swing.JButton();
        btnBaseHalfNote = new javax.swing.JButton();
        btnBaseQuarterNote = new javax.swing.JButton();
        btnBaseEighthNote = new javax.swing.JButton();
        btnBaseSixteenthNote = new javax.swing.JButton();
        btnBaseThirtysecondNote = new javax.swing.JButton();
        chkBaseTriplet = new javax.swing.JCheckBox();
        cmbBaseNote = new javax.swing.JComboBox<>();
        chkBaseInterval = new javax.swing.JCheckBox();
        btnBaseIntCon = new javax.swing.JButton();
        cmbBaseOctave = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        btnWholeRest1 = new javax.swing.JButton();
        btnHalfRest1 = new javax.swing.JButton();
        btnQuarterRest1 = new javax.swing.JButton();
        btnEighthRest1 = new javax.swing.JButton();
        btnSixteenthRest1 = new javax.swing.JButton();
        btnThirtysecondRest1 = new javax.swing.JButton();
        btnBaseNext = new javax.swing.JButton();
        lstSoundInfo = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lblSetupSheet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetupSheet.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabSetup.setEnabled(false);
        tabSetup.setName(""); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Page 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        jLabel1.setText("Number of Messures:");

        jLabel2.setText("Beats Per Messure:");

        btnSSNext.setText("Next");
        btnSSNext.setEnabled(false);
        btnSSNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSSNextActionPerformed(evt);
            }
        });

        txtMessureBeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMessureBeatsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMessureBeatsKeyTyped(evt);
            }
        });

        txtMessureNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMessureNumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMessureNumKeyTyped(evt);
            }
        });

        jLabel3.setText("Tempo:");

        txtTempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTempoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTempoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSSNext))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMessureBeats, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMessureNum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(75, 75, 75)
                                .addComponent(txtTempo)))
                        .addGap(0, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMessureNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMessureBeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnSSNext)
                .addContainerGap())
        );

        tabSetup.addTab("Score Setup", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Page 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        btnTrebleWholeNote.setText("Whole Note");
        btnTrebleWholeNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleWholeNoteActionPerformed(evt);
            }
        });

        btnTrebleHalfNote.setText("Half Note");
        btnTrebleHalfNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleHalfNoteActionPerformed(evt);
            }
        });

        btnTrebleQuarterNote.setText("Quarter Note");
        btnTrebleQuarterNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleQuarterNoteActionPerformed(evt);
            }
        });

        btnTrebleEighthNote.setText("Eighth Note");
        btnTrebleEighthNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleEighthNoteActionPerformed(evt);
            }
        });

        btnTrebleSixteenthNote.setText("Sixteenth Note");
        btnTrebleSixteenthNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleSixteenthNoteActionPerformed(evt);
            }
        });

        btnTrebleThirtysecondNote.setText("Thirty-Second Note");
        btnTrebleThirtysecondNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleThirtysecondNoteActionPerformed(evt);
            }
        });

        chkTrebleTriplet.setText("Triplet");

        cmbTrebleNote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A#", "B", "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#" }));
        cmbTrebleNote.setBorder(javax.swing.BorderFactory.createTitledBorder("Note"));

        chkTrebleInterval.setText("Interval");
        chkTrebleInterval.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkTrebleIntervalStateChanged(evt);
            }
        });

        btnTrebleIntCon.setText("Confirm");
        btnTrebleIntCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleIntConActionPerformed(evt);
            }
        });

        cmbTrebleOctave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbTrebleOctave.setBorder(javax.swing.BorderFactory.createTitledBorder("Octave"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTrebleWholeNote, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(btnTrebleEighthNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTrebleHalfNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrebleSixteenthNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTrebleThirtysecondNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrebleQuarterNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbTrebleNote, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTrebleOctave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkTrebleTriplet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkTrebleInterval)
                        .addGap(18, 18, 18)
                        .addComponent(btnTrebleIntCon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrebleQuarterNote)
                    .addComponent(btnTrebleHalfNote)
                    .addComponent(btnTrebleWholeNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrebleSixteenthNote)
                    .addComponent(btnTrebleThirtysecondNote)
                    .addComponent(btnTrebleEighthNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTrebleOctave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkTrebleTriplet)
                            .addComponent(chkTrebleInterval)
                            .addComponent(btnTrebleIntCon)))
                    .addComponent(cmbTrebleNote, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        btnTrebleWholeRest.setText("Whole Rest");
        btnTrebleWholeRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleWholeRestActionPerformed(evt);
            }
        });

        btnTrebleHalfRest.setText("Half Rest");
        btnTrebleHalfRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleHalfRestActionPerformed(evt);
            }
        });

        btnTrebleQuarterRest.setText("Quarter Rest");
        btnTrebleQuarterRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleQuarterRestActionPerformed(evt);
            }
        });

        btnTrebleEighthRest.setText("Eighth Rest");
        btnTrebleEighthRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleEighthRestActionPerformed(evt);
            }
        });

        btnTrebleSixteenthRest.setText("Sixteenth Rest");
        btnTrebleSixteenthRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleSixteenthRestActionPerformed(evt);
            }
        });

        btnTrebleThirtysecondRest.setText("Thirty-Second Rest");
        btnTrebleThirtysecondRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleThirtysecondRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTrebleWholeRest, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnTrebleEighthRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTrebleHalfRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrebleSixteenthRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTrebleThirtysecondRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrebleQuarterRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrebleQuarterRest)
                    .addComponent(btnTrebleHalfRest)
                    .addComponent(btnTrebleWholeRest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrebleSixteenthRest)
                    .addComponent(btnTrebleThirtysecondRest)
                    .addComponent(btnTrebleEighthRest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTrebleNext.setText("Next");
        btnTrebleNext.setEnabled(false);
        btnTrebleNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrebleNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTrebleNext)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrebleNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSetup.addTab("Treble Clef", jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Page 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        btnBaseWholeNote.setText("Whole Note");
        btnBaseWholeNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseWholeNoteActionPerformed(evt);
            }
        });

        btnBaseHalfNote.setText("Half Note");
        btnBaseHalfNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseHalfNoteActionPerformed(evt);
            }
        });

        btnBaseQuarterNote.setText("Quarter Note");
        btnBaseQuarterNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseQuarterNoteActionPerformed(evt);
            }
        });

        btnBaseEighthNote.setText("Eighth Note");
        btnBaseEighthNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseEighthNoteActionPerformed(evt);
            }
        });

        btnBaseSixteenthNote.setText("Sixteenth Note");
        btnBaseSixteenthNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseSixteenthNoteActionPerformed(evt);
            }
        });

        btnBaseThirtysecondNote.setText("Thirty-Second Note");
        btnBaseThirtysecondNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseThirtysecondNoteActionPerformed(evt);
            }
        });

        chkBaseTriplet.setText("Triplet");

        cmbBaseNote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A#", "B", "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#" }));
        cmbBaseNote.setBorder(javax.swing.BorderFactory.createTitledBorder("Note"));

        chkBaseInterval.setText("Interval");
        chkBaseInterval.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBaseIntervalStateChanged(evt);
            }
        });

        btnBaseIntCon.setText("Confirm");
        btnBaseIntCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseIntConActionPerformed(evt);
            }
        });

        cmbBaseOctave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbBaseOctave.setBorder(javax.swing.BorderFactory.createTitledBorder("Octave"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBaseWholeNote, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(btnBaseEighthNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBaseHalfNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBaseSixteenthNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBaseThirtysecondNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBaseQuarterNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(cmbBaseNote, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBaseOctave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkBaseTriplet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkBaseInterval)
                        .addGap(18, 18, 18)
                        .addComponent(btnBaseIntCon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaseQuarterNote)
                    .addComponent(btnBaseHalfNote)
                    .addComponent(btnBaseWholeNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaseSixteenthNote)
                    .addComponent(btnBaseThirtysecondNote)
                    .addComponent(btnBaseEighthNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBaseOctave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBaseTriplet)
                            .addComponent(chkBaseInterval)
                            .addComponent(btnBaseIntCon)))
                    .addComponent(cmbBaseNote, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        btnWholeRest1.setText("Whole Rest");
        btnWholeRest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWholeRest1ActionPerformed(evt);
            }
        });

        btnHalfRest1.setText("Half Rest");
        btnHalfRest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHalfRest1ActionPerformed(evt);
            }
        });

        btnQuarterRest1.setText("Quarter Rest");
        btnQuarterRest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuarterRest1ActionPerformed(evt);
            }
        });

        btnEighthRest1.setText("Eighth Rest");
        btnEighthRest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEighthRest1ActionPerformed(evt);
            }
        });

        btnSixteenthRest1.setText("Sixteenth Rest");
        btnSixteenthRest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixteenthRest1ActionPerformed(evt);
            }
        });

        btnThirtysecondRest1.setText("Thirty-Second Rest");
        btnThirtysecondRest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirtysecondRest1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnWholeRest1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnEighthRest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHalfRest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSixteenthRest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThirtysecondRest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuarterRest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuarterRest1)
                    .addComponent(btnHalfRest1)
                    .addComponent(btnWholeRest1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSixteenthRest1)
                    .addComponent(btnThirtysecondRest1)
                    .addComponent(btnEighthRest1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBaseNext.setText("Next");
        btnBaseNext.setEnabled(false);
        btnBaseNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBaseNext)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBaseNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSetup.addTab("Base Clef", jPanel8);

        lstSoundInfo.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstSoundInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSetupSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSetupSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(lstSoundInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabSetup.getAccessibleContext().setAccessibleName("tab 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessureNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessureNumKeyTyped
        controller.integerTest(evt);
    }//GEN-LAST:event_txtMessureNumKeyTyped

    private void txtMessureBeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessureBeatsKeyTyped
        controller.integerTest(evt);
    }//GEN-LAST:event_txtMessureBeatsKeyTyped

    private void txtMessureNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessureNumKeyReleased
        controller.fieldCheck();
    }//GEN-LAST:event_txtMessureNumKeyReleased

    private void txtMessureBeatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessureBeatsKeyReleased
        controller.fieldCheck();
    }//GEN-LAST:event_txtMessureBeatsKeyReleased

    private void btnSSNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSSNextActionPerformed
        controller.nextTab();
    }//GEN-LAST:event_btnSSNextActionPerformed

    private void txtTempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempoKeyTyped
        controller.integerTest(evt);
    }//GEN-LAST:event_txtTempoKeyTyped

    private void txtTempoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempoKeyReleased
        controller.fieldCheck();
    }//GEN-LAST:event_txtTempoKeyReleased

    private void btnTrebleNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleNextActionPerformed
        controller.nextTab();
    }//GEN-LAST:event_btnTrebleNextActionPerformed

    private void btnTrebleWholeNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleWholeNoteActionPerformed
        controller.addTrebleNote(wholeNote, wholeNoteNum);
    }//GEN-LAST:event_btnTrebleWholeNoteActionPerformed

    private void btnTrebleHalfNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleHalfNoteActionPerformed
        controller.addTrebleNote(halfNote, halfNoteNum);
    }//GEN-LAST:event_btnTrebleHalfNoteActionPerformed

    private void btnTrebleQuarterNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleQuarterNoteActionPerformed
        controller.addTrebleNote(quarterNote, quarterNoteNum);
    }//GEN-LAST:event_btnTrebleQuarterNoteActionPerformed

    private void btnTrebleEighthNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleEighthNoteActionPerformed
        controller.addTrebleNote(eighthNote, eighthNoteNum);
    }//GEN-LAST:event_btnTrebleEighthNoteActionPerformed

    private void btnTrebleSixteenthNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleSixteenthNoteActionPerformed
        controller.addTrebleNote(sixteenthNote, sixteenthNoteNum);
    }//GEN-LAST:event_btnTrebleSixteenthNoteActionPerformed

    private void btnTrebleThirtysecondNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleThirtysecondNoteActionPerformed
        controller.addTrebleNote(thirtysecondNote, thirtysecondNoteNum);
    }//GEN-LAST:event_btnTrebleThirtysecondNoteActionPerformed

    private void btnTrebleIntConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleIntConActionPerformed
        controller.trebleIntervalMerge();
    }//GEN-LAST:event_btnTrebleIntConActionPerformed

    private void chkTrebleIntervalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkTrebleIntervalStateChanged
        controller.buttonUpdate();
    }//GEN-LAST:event_chkTrebleIntervalStateChanged

    private void btnTrebleWholeRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleWholeRestActionPerformed
        controller.addRest(wholeRest, wholeRestNum);
    }//GEN-LAST:event_btnTrebleWholeRestActionPerformed

    private void btnTrebleHalfRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleHalfRestActionPerformed
        controller.addRest(halfRest, halfRestNum);
    }//GEN-LAST:event_btnTrebleHalfRestActionPerformed

    private void btnTrebleQuarterRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleQuarterRestActionPerformed
        controller.addRest(quarterRest, quarterRestNum);
    }//GEN-LAST:event_btnTrebleQuarterRestActionPerformed

    private void btnTrebleEighthRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleEighthRestActionPerformed
        controller.addRest(eighthRest, eighthRestNum);
    }//GEN-LAST:event_btnTrebleEighthRestActionPerformed

    private void btnTrebleSixteenthRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleSixteenthRestActionPerformed
        controller.addRest(sixteenthRest, sixteenthRestNum);
    }//GEN-LAST:event_btnTrebleSixteenthRestActionPerformed

    private void btnTrebleThirtysecondRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrebleThirtysecondRestActionPerformed
        controller.addRest(thirtysecondRest,thirtysecondRestNum);
    }//GEN-LAST:event_btnTrebleThirtysecondRestActionPerformed

    private void btnBaseWholeNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseWholeNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaseWholeNoteActionPerformed

    private void btnBaseHalfNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseHalfNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaseHalfNoteActionPerformed

    private void btnBaseQuarterNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseQuarterNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaseQuarterNoteActionPerformed

    private void btnBaseEighthNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseEighthNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaseEighthNoteActionPerformed

    private void btnBaseSixteenthNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseSixteenthNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaseSixteenthNoteActionPerformed

    private void btnBaseThirtysecondNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseThirtysecondNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaseThirtysecondNoteActionPerformed

    private void chkBaseIntervalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBaseIntervalStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBaseIntervalStateChanged

    private void btnBaseIntConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseIntConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaseIntConActionPerformed

    private void btnWholeRest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWholeRest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWholeRest1ActionPerformed

    private void btnHalfRest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHalfRest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHalfRest1ActionPerformed

    private void btnQuarterRest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuarterRest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuarterRest1ActionPerformed

    private void btnEighthRest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEighthRest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEighthRest1ActionPerformed

    private void btnSixteenthRest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixteenthRest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSixteenthRest1ActionPerformed

    private void btnThirtysecondRest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirtysecondRest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThirtysecondRest1ActionPerformed

    private void btnBaseNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaseNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaseEighthNote;
    private javax.swing.JButton btnBaseHalfNote;
    private javax.swing.JButton btnBaseIntCon;
    private javax.swing.JButton btnBaseNext;
    private javax.swing.JButton btnBaseQuarterNote;
    private javax.swing.JButton btnBaseSixteenthNote;
    private javax.swing.JButton btnBaseThirtysecondNote;
    private javax.swing.JButton btnBaseWholeNote;
    private javax.swing.JButton btnEighthRest1;
    private javax.swing.JButton btnHalfRest1;
    private javax.swing.JButton btnQuarterRest1;
    private javax.swing.JButton btnSSNext;
    private javax.swing.JButton btnSixteenthRest1;
    private javax.swing.JButton btnThirtysecondRest1;
    private javax.swing.JButton btnTrebleEighthNote;
    private javax.swing.JButton btnTrebleEighthRest;
    private javax.swing.JButton btnTrebleHalfNote;
    private javax.swing.JButton btnTrebleHalfRest;
    private javax.swing.JButton btnTrebleIntCon;
    private javax.swing.JButton btnTrebleNext;
    private javax.swing.JButton btnTrebleQuarterNote;
    private javax.swing.JButton btnTrebleQuarterRest;
    private javax.swing.JButton btnTrebleSixteenthNote;
    private javax.swing.JButton btnTrebleSixteenthRest;
    private javax.swing.JButton btnTrebleThirtysecondNote;
    private javax.swing.JButton btnTrebleThirtysecondRest;
    private javax.swing.JButton btnTrebleWholeNote;
    private javax.swing.JButton btnTrebleWholeRest;
    private javax.swing.JButton btnWholeRest1;
    private javax.swing.JCheckBox chkBaseInterval;
    private javax.swing.JCheckBox chkBaseTriplet;
    private javax.swing.JCheckBox chkTrebleInterval;
    private javax.swing.JCheckBox chkTrebleTriplet;
    private javax.swing.JComboBox<String> cmbBaseNote;
    private javax.swing.JComboBox<String> cmbBaseOctave;
    private javax.swing.JComboBox<String> cmbTrebleNote;
    private javax.swing.JComboBox<String> cmbTrebleOctave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblSetupSheet;
    private java.awt.List lstSoundInfo;
    private javax.swing.JTabbedPane tabSetup;
    private javax.swing.JTextField txtMessureBeats;
    private javax.swing.JTextField txtMessureNum;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
